name: instachat
description: A working replica of Instagram DMs and stories.

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <2.12.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  emojis: ^0.9.3
  flutter_dotenv: ^3.1.0
  google_sign_in: ^4.5.1
  http: ^0.12.2
  image_picker: ^0.6.7+21
  path_provider: ^1.6.27
  provider: ^4.3.2
  uuid: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
