name: instachat
description: A working replica of Instagram DMs and stories.

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  flutter_dotenv: ^3.1.0
  google_sign_in: ^5.0.0-nullsafety
  http: ^0.13.0
  image_picker: ^0.7.0
  path_provider: ^2.0.0-nullsafety.1
  provider: ^5.0.0-nullsafety.5
  uuid: ^3.0.0-nullsafety.1
  web_socket_channel: ^2.0.0

dependency_overrides:
  dio: # https://github.com/flutterchina/dio/issues/1002
    git:
      url: https://github.com/TitanKing/dio
      ref: null-safety
      path: dio
  flutter_dotenv: # https://github.com/java-james/flutter_dotenv/pull/24
    git:
      url: https://github.com/ngxingyu/flutter_dotenv
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic
