name: instachat
description: A working replica of Instagram DMs and stories.

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  emojis: ^0.9.3
  flutter_dotenv: ^3.1.0
  google_sign_in: ^5.0.2
  http: ^0.13.1
  image_picker: ^0.7.4
  path_provider: ^2.0.1
  provider: ^5.0.0
  uuid: ^3.0.4
  web_socket_channel: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
