name: Flutter deploy

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        run: |
          sudo snap install flutter --classic
          flutter upgrade

      - name: Build
        run: |
          cd instachat

          cat <<EOF > .env
          DOMAIN=api.instachat.live
          S3_URL=https://instachat-images.s3.amazonaws.com
          EOF

          sed -i 's/YOUR_GOOGLE_SIGN_IN_OAUTH_CLIENT_ID.apps.googleusercontent.com/${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}/' ./web/index.html
          flutter build web --web-renderer canvaskit
          echo "www.instachat.live" >> ./build/web/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./instachat/build/web
